// build.rs
//
// Two jobs:
//
// 1. Resolve the rendering backend once and expose it as a single cfg the crate
//    gates on (`backend_metal` / `backend_dx` / `backend_vk`), via the shared
//    `concinnity-toolchain` helper.
//
// 2. Detect the optional graphics SDKs and, because this crate owns the final
//    `concinnity` binary, bundle their runtime DLLs next to the artifact and
//    emit the Agility linker exports (the `D3D12SDKVersion` / `D3D12SDKPath`
//    statics those exports name are defined in src/main.rs). That is
//    `SdkOptions { bundle_dlls: true }`.
//
// The C FFI header (../include/concinnity.h) is generated by the concinnity-app
// crate, which owns the extern "C" surface.

use concinnity_toolchain::{SdkOptions, emit_backend_cfg, emit_check_cfgs, setup_graphics_sdks};

fn main() {
    emit_check_cfgs();
    let backend = emit_backend_cfg();
    setup_graphics_sdks(backend, SdkOptions { bundle_dlls: true });
}
