// Emission: the extracted types written back out as a Rust source file holding
// one `&'static`-based constant, for a build script to drop in `OUT_DIR` and
// the crate to `include!`.

use super::TableSpec;
use super::model::{DocFieldType, DocShape, DocType};
use std::fmt::Write;

pub(super) fn table(types: &[DocType], spec: &TableSpec) -> String {
    let path = spec.model_path;
    let mut out = String::new();
    out.push_str("// Auto-generated by this crate's build script - do not edit.\n\n");
    for line in spec.doc.lines() {
        let _ = writeln!(out, "///{}{line}", if line.is_empty() { "" } else { " " });
    }
    let _ = writeln!(
        out,
        "pub const {}: &[{path}::DocType] = &[",
        spec.const_name
    );
    for t in types {
        let _ = writeln!(
            out,
            "    {path}::DocType {{ name: {:?}, doc: {:?}, shape: {} }},",
            t.name,
            t.doc,
            shape(&t.shape, path)
        );
    }
    out.push_str("];\n");
    out
}

fn shape(shape: &DocShape, path: &str) -> String {
    let mut out = String::new();
    match shape {
        DocShape::Fields(fields) => {
            let _ = write!(out, "{path}::DocShape::Fields(&[");
            for f in fields {
                let _ = write!(
                    out,
                    "{path}::DocField {{ key: {:?}, doc: {:?}, ty: {}, optional: {}, \
                     default: {} }}, ",
                    f.key,
                    f.doc,
                    field_type(&f.ty, path),
                    f.optional,
                    option_str(f.default.as_deref()),
                );
            }
            out.push_str("])");
        }
        DocShape::Values(values) => {
            let _ = write!(out, "{path}::DocShape::Values(&[");
            for v in values {
                let _ = write!(
                    out,
                    "{path}::DocValue {{ value: {:?}, doc: {:?} }}, ",
                    v.value, v.doc
                );
            }
            out.push_str("])");
        }
    }
    out
}

fn field_type(ty: &DocFieldType, path: &str) -> String {
    let variant = match ty {
        DocFieldType::Bool => "Bool".to_string(),
        DocFieldType::Float => "Float".to_string(),
        DocFieldType::Integer => "Integer".to_string(),
        DocFieldType::Str => "Str".to_string(),
        DocFieldType::Object => "Object".to_string(),
        DocFieldType::Name(name) => format!("Name({name:?})"),
        DocFieldType::Array { elem, len } => format!(
            "Array {{ elem: &{}, len: {} }}",
            field_type(elem, path),
            option_usize(*len)
        ),
    };
    format!("{path}::DocFieldType::{variant}")
}

fn option_str(value: Option<&str>) -> String {
    match value {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_string(),
    }
}

fn option_usize(value: Option<usize>) -> String {
    match value {
        Some(v) => format!("Some({v})"),
        None => "None".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::super::model::{DocField, DocValue};
    use super::*;

    fn spec() -> TableSpec<'static> {
        TableSpec {
            const_name: "DOCS",
            doc: "Every documented type.",
            model_path: "doc_model",
        }
    }

    #[test]
    fn a_struct_emits_a_field_list() {
        let types = vec![DocType {
            name: "Prop".to_string(),
            doc: "A \"prop\".".to_string(),
            shape: DocShape::Fields(vec![DocField {
                key: "mesh".to_string(),
                doc: String::new(),
                ty: DocFieldType::Str,
                optional: true,
                default: Some("null".to_string()),
            }]),
        }];
        let src = table(&types, &spec());
        assert!(src.contains("/// Every documented type."));
        assert!(src.contains("pub const DOCS: &[doc_model::DocType] = &["));
        assert!(src.contains(r#"name: "Prop", doc: "A \"prop\".""#));
        assert!(src.contains("doc_model::DocShape::Fields(&["));
        assert!(src.contains(
            r#"doc_model::DocField { key: "mesh", doc: "", ty: doc_model::DocFieldType::Str, optional: true, default: Some("null") }"#
        ));
    }

    #[test]
    fn a_nested_array_emits_promoted_references() {
        let types = vec![DocType {
            name: "Wave".to_string(),
            doc: String::new(),
            shape: DocShape::Fields(vec![DocField {
                key: "rows".to_string(),
                doc: String::new(),
                ty: DocFieldType::Array {
                    elem: Box::new(DocFieldType::Array {
                        elem: Box::new(DocFieldType::Float),
                        len: Some(2),
                    }),
                    len: None,
                },
                optional: false,
                default: None,
            }]),
        }];
        let src = table(&types, &spec());
        assert!(src.contains(
            "doc_model::DocFieldType::Array { elem: &doc_model::DocFieldType::Array \
             { elem: &doc_model::DocFieldType::Float, len: Some(2) }, len: None }"
        ));
    }

    #[test]
    fn an_enum_emits_a_value_list() {
        let types = vec![DocType {
            name: "AaMode".to_string(),
            doc: String::new(),
            shape: DocShape::Values(vec![DocValue {
                value: "taa".to_string(),
                doc: "Temporal.".to_string(),
            }]),
        }];
        let src = table(&types, &spec());
        assert!(src.contains(r#"doc_model::DocShape::Values(&[doc_model::DocValue { value: "taa", doc: "Temporal." }, ])"#));
    }

    #[test]
    fn an_empty_table_is_still_a_valid_constant() {
        let src = table(&[], &spec());
        assert!(src.contains("pub const DOCS: &[doc_model::DocType] = &[\n];\n"));
    }
}
