#pragma once

/* Generated by cbindgen from src/ffi.rs. Do not edit. */

// Why a `cn_` call failed, or [`Ok`](CnError::Ok) when it did not.
//
// The engine reports a structured error with a cause chain to its Rust
// callers; a C host cannot hold one, so this is what a failure flattens to
// here, at the boundary, with the full chain going to the log.
typedef enum {
  // The call succeeded.
  CnError_Ok = 0,
  // A pointer argument was null, or a string was not UTF-8.
  CnError_InvalidArgument = 1,
  // `cn_init` has not run, so there is no host state to act on.
  CnError_NotInitialized = 2,
  // The root names nothing a world can be read from.
  CnError_NoWorldData = 3,
  // The world data is present but did not load.
  CnError_UnreadableWorldData = 4,
  // The world loaded but refused to start.
  CnError_StartFailed = 5,
} CnError;

// What one step of a world reports.
typedef enum {
  // The world is running; step it again next refresh.
  CnStep_Continue = 0,
  // The world reached its own end.
  CnStep_Done = 1,
  // The world asked to stop.
  CnStep_Stopped = 2,
  // No world is open, so there was nothing to step.
  CnStep_NoWorld = -1,
} CnStep;

// Initialize logging and the host state. Call once, from the thread that owns
// the view, before any other `cn_` function.
//
// The log level is not a parameter: it follows the same default the player
// uses and `RUST_LOG` overrides it.
void cn_init(void);

// Open the built world under `root` and render it into `view`.
//
// `root` is a NUL-terminated absolute path to the directory holding the
// world's `data/`. `view` is the platform's view pointer, an `NSView*` on
// macOS and a `UIView*` on iOS, and must outlive the world. A non-zero
// `pump_events` asks the engine to drain the platform's event queue during a
// step, for a host that does not run an event loop of its own; pass 0 when
// the host dispatches input itself, which is the usual case.
//
// Replaces whatever world was open. Returns [`CnError::Ok`] on success, and
// otherwise the code for why it failed, with the full cause chain logged.
//
// # Safety
//
// `root` must be a NUL-terminated C string, and `view` a live view pointer of
// the platform's type, both valid for the duration of the call.
CnError cn_world_open(const char *root, void *view, int pump_events);

// Step the open world once. Returns a [`CnStep`].
CnStep cn_world_step(void);

// Close the open world, releasing its GPU resources and detaching it from the
// host's view. Does nothing when no world is open.
void cn_world_close(void);
