[package]
name = "example-common"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "example_common"
path = "lib.rs"

[features]
vulkan = ["concinnity-engine/vulkan", "concinnity-shader/vulkan"]

[dependencies]
concinnity-engine = { path = "../../crates/concinnity-engine" }
concinnity-cook = { path = "../../crates/concinnity-cook" }
concinnity-shader = { path = "../../crates/concinnity-shader" }
