//! Build-time compilation of the single-source `.slang` engine shaders into
//! bytes the binary carries.
//!
//! The Metal backend has always done this (`metal_shaders`); this is the same
//! idea for the targets whose artifacts are plain byte blobs rather than
//! metallibs. What it buys is not startup time but self-containment: a binary
//! that embeds its shaders needs no `slangc` on the host that runs it, which is
//! otherwise a hard runtime dependency of the DirectX and Vulkan backends.
//!
//! The declarations come from `concinnity_render::slang_programs`, the same
//! table the renderer iterates, so the text compiled here is the text the
//! renderer would have compiled. Where slangc is absent the generated lookup
//! answers `None` for everything and the renderer compiles at init exactly as
//! before -- a build host without the compiler still produces a working binary,
//! just one that needs slangc wherever it runs.

use std::path::{Path, PathBuf};

use concinnity_slang as slang;

/// One program to precompile: the name the renderer looks it up by, the
/// assembled source text, the entry point, and what slangc should emit.
pub struct SlangArtifact<'a> {
    /// Lookup key. Must match what the renderer asks for.
    pub name: String,
    /// Fully assembled source, defines and fragments already spliced.
    pub source: String,
    /// Entry point compiled out of `source`.
    pub entry: &'a str,
    /// File name slangc reports diagnostics against.
    pub file_name: &'a str,
    /// What slangc emits.
    pub target: slang::SlangTarget,
}

/// Compile every artifact into `OUT_DIR` and generate `generated` beside it: a
/// `fn <lookup>(name: &str) -> Option<(u64, &'static [u8])>` mapping each name
/// to the digest of the source it was built from and its embedded bytes.
///
/// The digest is what makes the artifact safe to use: the caller compares it
/// against the source it just assembled and compiles instead on a mismatch, so
/// an edited shader is never shadowed by a stale build-time copy.
///
/// A program that fails to compile is a hard error: a broken shader must fail
/// the build rather than surface at renderer init. A *missing compiler* is not,
/// and emits the stub lookup behind a cargo warning.
pub fn precompile_slang_artifacts(artifacts: &[SlangArtifact<'_>], generated: &str, lookup: &str) {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join(generated);

    if slang::slangc_path().is_none() {
        println!(
            "cargo:warning=slangc not found; the engine's single-source shaders will compile \
             at startup, which needs slangc on every host that runs this binary. Install a \
             Slang release (https://github.com/shader-slang/slang/releases) to embed them."
        );
        std::fs::write(&generated, stub_lookup_source(lookup)).expect("write shader lookup");
        return;
    }

    let art_dir = out_dir.join("engine_slang");
    std::fs::create_dir_all(&art_dir).expect("create engine_slang dir");
    let mut entries = Vec::with_capacity(artifacts.len());
    for artifact in artifacts {
        let job = slang::SlangJob {
            source: &artifact.source,
            file_name: artifact.file_name,
            entries: &[artifact.entry],
            target: artifact.target,
        };
        let bytes = slang::compile(&job, &art_dir)
            .unwrap_or_else(|e| panic!("precompiling {}: {e}", artifact.name));
        let path = art_dir.join(&artifact.name);
        std::fs::write(&path, bytes).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
        entries.push((
            artifact.name.clone(),
            concinnity_render::slang_source::source_digest(&artifact.source),
            path,
        ));
    }
    std::fs::write(&generated, lookup_source(&entries, lookup)).expect("write shader lookup");
}

// Generated lookup mapping a program name to its embedded bytes. Kept pure
// (names and paths in, source out) for unit testing.
fn lookup_source(entries: &[(String, u64, PathBuf)], lookup: &str) -> String {
    let mut src = format!(
        "// @generated by concinnity-toolchain::precompile_slang_artifacts\n\
         pub(crate) fn {lookup}(name: &str) -> Option<(u64, &'static [u8])> {{\n\
         \x20   match name {{\n"
    );
    for (name, digest, path) in entries {
        src.push_str(&format!(
            "        {name:?} => Some(({digest}u64, include_bytes!({:?}))),\n",
            path.display().to_string()
        ));
    }
    src.push_str("        _ => None,\n    }\n}\n");
    src
}

// Fallback when no slangc is available at build time.
fn stub_lookup_source(lookup: &str) -> String {
    format!(
        "// @generated by concinnity-toolchain::precompile_slang_artifacts (no slangc)\n\
         pub(crate) fn {lookup}(_name: &str) -> Option<(u64, &'static [u8])> {{\n\
         \x20   None\n\
         }}\n"
    )
}

/// Emit a rerun directive per shader file, so an edit to any of them
/// recompiles the artifacts rather than replaying stale bytes.
pub fn watch_shader_dir(dir: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_source_maps_each_entry_and_falls_through() {
        let entries = vec![
            (
                "vert.dxil".to_string(),
                7u64,
                PathBuf::from("/out/vert.dxil"),
            ),
            (
                "frag.dxil".to_string(),
                9u64,
                PathBuf::from("/out/frag.dxil"),
            ),
        ];
        let src = lookup_source(&entries, "embedded_dxil");
        assert!(src.contains("fn embedded_dxil"));
        assert!(src.contains("\"vert.dxil\" => Some((7u64, include_bytes!(\"/out/vert.dxil\")))"));
        assert!(src.contains("\"frag.dxil\" => Some((9u64, include_bytes!(\"/out/frag.dxil\")))"));
        assert!(src.contains("_ => None"));
    }

    // Without slangc the lookup must still compile and answer for every name,
    // so the renderer falls back to compiling rather than failing to build.
    #[test]
    fn stub_lookup_returns_none_for_everything() {
        let src = stub_lookup_source("embedded_dxil");
        assert!(src.contains("fn embedded_dxil"));
        assert!(src.contains("None"));
        assert!(!src.contains("include_bytes!"));
    }

    // The two share a signature, so a build with slangc and one without are
    // drop-in replacements for each other.
    #[test]
    fn the_stub_and_the_real_lookup_share_a_signature() {
        let sig = "(name: &str) -> Option<(u64, &'static [u8])>";
        assert!(lookup_source(&[], "f").contains(&format!("fn f{sig}")));
        assert!(
            stub_lookup_source("f").contains("fn f(_name: &str) -> Option<(u64, &'static [u8])>")
        );
    }
}
