[package]
name = "concinnity-docs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
name = "concinnity_docs"

[dependencies]

[build-dependencies]
syn = { version = "2", features = ["full", "parsing"] }
concinnity-world = { path = "../concinnity-world" }

[lints]
workspace = true
