[package]
name = "concinnity-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "concinnity_store"
path = "src/lib.rs"

[dependencies]
concinnity-core = { path = "../concinnity-core" }
concinnity-blob = { path = "../concinnity-blob" }

tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.25.0"

[lints]
workspace = true
