[package]
name = "concinnity-audio"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Audio system for the Concinnity engine"
keywords = ["gamedev", "audio", "concinnity"]
categories = ["game-engines", "multimedia::audio"]
include = [
    "/src",
]

[lib]
name = "concinnity_audio"

[dependencies]
concinnity-core = { workspace = true }

kira = "0.12"
mint = "0.5"
tracing = "0.1.44"

[dev-dependencies]
concinnity-store = { workspace = true }

[lints]
workspace = true
