// src/ecs/mod.rs
//
// Renderer-free ecs metadata + identity layer shared by the build / validate
// pipeline and the client runtime: the asset-identity interner (`asset_id`),
// the `Component` metadata trait, and the plain data types the registry and
// blob format are built from (`Registration`, `AssetOrigin`, `AssetPayload`,
// `PayloadLocator`, `BlobAssetDef`, `AssetKind`).
//
// The runtime half (the `System` behavior trait, `PipelineContext`, `World`,
// the value enums (`ComponentAsset` / `SystemAsset`), and the registry macros)
// lives in the client crate's `ecs` module, which re-exports everything here
// under the historical `crate::ecs::*` paths.
pub mod asset_id;
mod registry;

use crate::blob::BlobData;
use crate::ecs::asset_id::AssetId;
use crate::gfx::profile::FrameProfile;
use crate::result::CnResult;
pub use concinnity_eas::{Entity, EventCursor, EventStore, Events, Resources};

// Runtime asset-registry types, generated by the macros further down (invoked
// in `registry`). Re-exported here so the rest of the crate (and the client,
// which re-exports this module under `crate::ecs::*`) can keep using the
// historical `crate::ecs::*` paths. The authoring `ComponentType` registry is
// built from the same component list in the build crate. The runtime
// `SystemAsset` enum is generated client-side from the `System` behavior trait.
pub use registry::{ComponentAsset, ComponentSlot, ComponentStorage, ComponentTag};

// Where an asset comes from and whether it persists to a blob.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum AssetOrigin {
    External,
    RuntimeOnly,
    BuildOnly,
}

// Whether the asset has a compiled binary payload packed into a .cnb blob.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum AssetPayload {
    None,
    Compiled,
}

// Static metadata for a Component or System type.
#[derive(Debug, Clone, serde::Serialize)]
pub struct Registration {
    pub type_name: &'static str,
    pub origin: AssetOrigin,
    pub payload: AssetPayload,
    pub default_args: Option<serde_json::Value>,
}

impl Registration {
    pub fn addable(&self) -> bool {
        self.origin == AssetOrigin::External
    }

    #[allow(dead_code)]
    pub fn serializable(&self) -> bool {
        self.origin != AssetOrigin::RuntimeOnly
    }

    #[allow(dead_code)]
    pub fn runtime_present(&self) -> bool {
        self.origin != AssetOrigin::BuildOnly
    }

    pub fn needs_compilation(&self) -> bool {
        self.payload == AssetPayload::Compiled
    }
}

// Component -- pure serializable data, no behavior.
pub trait Component: Sized + Send + std::fmt::Debug + 'static {
    const NAME: &'static str;
    const ORIGIN: AssetOrigin = AssetOrigin::RuntimeOnly;
    const PAYLOAD: AssetPayload = AssetPayload::None;

    type Args: serde::Serialize + serde::de::DeserializeOwned + Default;
    #[allow(dead_code)]
    fn to_args(&self) -> Self::Args;
    fn from_args(args: Self::Args) -> Self;

    // Called after construction to inject the payload locator from the blob def.
    // Only meaningful for components with `AssetPayload::Compiled`.
    // The default implementation does nothing (correct for most components).
    fn inject_locator(&mut self, _locator: PayloadLocator) {}

    // Called after construction to inject the asset's identity from the blob
    // def. Only meaningful for components that look themselves up by id at
    // runtime (Prop, Mesh, Texture, Material, Model, Font, TextLabel, etc.).
    // The default implementation does nothing.
    fn inject_name(&mut self, _id: AssetId) {}

    fn registration() -> Registration {
        Registration {
            type_name: Self::NAME,
            origin: Self::ORIGIN,
            payload: Self::PAYLOAD,
            default_args: serde_json::to_value(Self::Args::default()).ok(),
        }
    }

    // Fields of this asset's `Args` that are asset references, as
    // `(field_name, target_type_name)`. These are `Option<AssetId>` fields authored
    // in world.jsonl as the referenced asset's name; the target type is not in the
    // type system (`AssetId` is type-erased), so an asset that has references
    // declares them here. Authoring tools use this to offer a picker of existing
    // assets of the target type instead of a free text box. Default: none.
    fn ref_fields() -> &'static [(&'static str, &'static str)] {
        &[]
    }
}

// Points to an asset's compiled binary payload within the data blob files.
// Defined in the schema crate because blob-backed asset structs carry it as a
// `#[serde(skip)]` field; re-exported here under its historical path.
pub use concinnity_asset::PayloadLocator;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct BlobAssetDef {
    // The asset's interned identity. `None` for unnamed runtime-only assets.
    // Injected into the component at load time via `Component::inject_name`.
    pub name: Option<AssetId>,
    pub kind: AssetKind,
    pub discriminant: u8,
    #[serde(with = "serde_bytes")]
    pub args_bytes: Vec<u8>,
    pub payload: Option<PayloadLocator>,
}

// The blob carries only components: every system is internal client code,
// constructed at runtime from world content, never serialized. This kind is
// kept as the single discriminator the blob format records per asset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum AssetKind {
    Component,
}

// PipelineContext -- systems' view of the world during a tick. Renderer-free:
// it exposes typed component storage, the in-memory blob payload store, and the
// per-frame profiler. The client `World` constructs one each tick and passes it
// to every `System::step`.
pub struct PipelineContext<'a> {
    // Per-type component storage. Systems should not access this directly;
    // use `query`, `query_mut`, `drain`, or `push` instead.
    pub components: &'a mut ComponentStorage,
    // In-memory blob payload store. Systems use `read_payload` to fetch
    // compiled binary data, then call `release_blob` when done with it.
    #[allow(dead_code)]
    pub blob: &'a mut BlobData,
    // Per-frame profiling data. `World::step` records each system's CPU step
    // time here; `GraphicsSystem` writes the backend `RenderStats` after its
    // draw call, and `StatHud` reads it back to drive the on-screen HUD.
    pub profile: &'a mut FrameProfile,
    // Type-keyed engine singletons (e.g. the per-frame FrameInput snapshot),
    // accessed via `resource` / `resource_mut` / `insert_resource`. Events live
    // here too, inside a single `EventStore` resource that owns one `Events<E>`
    // queue per event type, reached via `events` / `events_mut`.
    pub resources: &'a mut Resources,
}

impl<'a> PipelineContext<'a> {
    // Immutable iteration over all components of type C.
    #[allow(dead_code)]
    pub fn query<C: ComponentSlot>(&self) -> std::slice::Iter<'_, C> {
        C::slot(self.components).iter()
    }

    // Iterate all components of type C paired with their owning Entity.
    #[allow(dead_code)]
    pub fn query_with_entity<C: ComponentSlot>(&self) -> impl Iterator<Item = (Entity, &C)> {
        C::slot(self.components).iter_with_entities()
    }

    // Mutable iteration over all components of type C.
    #[allow(dead_code)]
    pub fn query_mut<C: ComponentSlot>(&mut self) -> std::slice::IterMut<'_, C> {
        self.components.values_mut::<C>().iter_mut()
    }

    // Mutable slice of all components of type C. Unlike `query_mut` this
    // exposes the backing storage as a slice, which a system can hand to the
    // job pool for parallel per-component work.
    #[allow(dead_code)]
    pub fn query_slice_mut<C: ComponentSlot>(&mut self) -> &mut [C] {
        self.components.values_mut::<C>()
    }

    // Remove and return all components of type C, despawning each removed
    // row's Entity so the indices recycle.
    pub fn drain<C: ComponentSlot>(&mut self) -> Vec<C> {
        self.components.drain::<C>()
    }

    // Push a runtime-produced component into the matching typed column,
    // minting a fresh Entity for it. Preferred over reaching into
    // `self.components` directly.
    #[allow(dead_code)]
    pub fn push<C: ComponentSlot>(&mut self, c: C) {
        self.components.push_typed(c);
    }

    // Add a component to an existing entity, so an entity can own more than one
    // component. The entity must be alive and must not already have C. Allowed
    // dead because the caller is in the client crate (the load-time Prop
    // decomposition); core itself has no systems.
    #[allow(dead_code)]
    pub fn insert<C: ComponentSlot>(&mut self, entity: Entity, c: C) {
        self.components.insert_typed(entity, c);
    }

    // Remove a component from an entity, returning it if present. The entity
    // keeps its other components. Allowed dead for the same cross-crate reason
    // as `insert` (the client toggles the Held tag on pickup/drop).
    #[allow(dead_code)]
    pub fn remove<C: ComponentSlot>(&mut self, entity: Entity) -> Option<C> {
        self.components.remove_typed::<C>(entity)
    }

    // Remove an entity entirely: swap-remove its row from every component
    // column and recycle its id (a stale handle to it then reads as dead). A
    // no-op on an already-dead or unknown entity. Allowed dead for the same
    // cross-crate reason as `insert` (the client despawns entities at runtime
    // from the GraphicsSystem).
    #[allow(dead_code)]
    pub fn despawn(&mut self, entity: Entity) {
        self.components.despawn(entity);
    }

    // Whether an entity is still live (not despawned, matching generation).
    // Allowed dead for the same cross-crate reason as `insert` (the client
    // reaps a despawned entity's physics body in PhysicsSystem).
    #[allow(dead_code)]
    pub fn is_alive(&self, entity: Entity) -> bool {
        self.components.is_alive(entity)
    }

    // Borrow one entity's component C read-only. Allowed dead for the same
    // cross-crate reason as `insert` (the client reads Transform / Held by
    // entity in the physics, camera, and audio systems).
    #[allow(dead_code)]
    pub fn get<C: ComponentSlot>(&self, entity: Entity) -> Option<&C> {
        self.components.get::<C>(entity)
    }

    // Read-only join over two component types: iterate the first type's rows
    // and yield both refs for every entity that also has the second. Allowed
    // dead for the same cross-crate reason as `insert`.
    #[allow(dead_code)]
    pub fn join2<A: ComponentSlot, B: ComponentSlot>(
        &self,
    ) -> impl Iterator<Item = (Entity, &A, &B)> {
        self.components.join2::<A, B>()
    }

    // Mutably borrow one entity's component C (a propagation pass writing a
    // single entity's value). Allowed dead for the same cross-crate reason as
    // `insert`.
    #[allow(dead_code)]
    pub fn get_mut<C: ComponentSlot>(&mut self, entity: Entity) -> Option<&mut C> {
        self.components.get_mut::<C>(entity)
    }

    // Borrow the singleton resource of type T, if present.
    pub fn resource<T: std::any::Any>(&self) -> Option<&T> {
        self.resources.get::<T>()
    }

    // Mutably borrow the singleton resource of type T, if present.
    #[allow(dead_code)]
    pub fn resource_mut<T: std::any::Any>(&mut self) -> Option<&mut T> {
        self.resources.get_mut::<T>()
    }

    // Install (or replace) the singleton resource of type T, returning the
    // previous instance if one was present.
    pub fn insert_resource<T: std::any::Any>(&mut self, value: T) -> Option<T> {
        self.resources.insert(value)
    }

    // Borrow the event queue for event type E, if any events of that type have
    // been registered.
    #[allow(dead_code)]
    pub fn events<E: 'static>(&self) -> Option<&Events<E>> {
        self.resources.get::<EventStore>()?.get::<E>()
    }

    // Mutably borrow the event queue for event type E, creating an empty one on
    // first access so writers and readers never miss it. All queues live in the
    // `EventStore` resource, which the frame driver rotates wholesale.
    #[allow(dead_code)]
    pub fn events_mut<E: 'static>(&mut self) -> &mut Events<E> {
        if !self.resources.contains::<EventStore>() {
            self.resources.insert(EventStore::new());
        }
        self.resources
            .get_mut::<EventStore>()
            .expect("EventStore was just inserted")
            .get_mut_or_create::<E>()
    }

    // Read the compiled payload bytes for a locator.
    //
    // Takes `&mut self` because an overflow blob is read from disk lazily on
    // first access. Returns an error if the blob was released, the locator is
    // out of range, or the on-demand load fails.
    #[allow(dead_code)]
    pub fn read_payload(&mut self, locator: &PayloadLocator) -> Result<&[u8], CnResult> {
        self.blob.read(locator)
    }

    // Release the in-memory payload for an entire blob once all systems
    // that need it have finished (e.g. after GPU upload).
    //
    // See `BlobData::release` for semantics.
    #[allow(dead_code)]
    pub fn release_blob(&mut self, blob_index: u32) {
        self.blob.release(blob_index);
    }
}

// Asset registration macros
//
// `define_components!` builds the runtime half of the registry (invoked in
// `crate::ecs::registry` over the shared `for_each_component!` list): the
// `ComponentAsset` value enum via `__define_asset_kind!`, plus the blob loader
// and ECS storage. The authoring `ComponentType` registry is built from the same
// list in the build crate. The runtime `SystemAsset` enum is generated
// separately, client-side, by `define_system_assets!`.

// Internal helper. Emits the runtime `<Kind>Asset` value enum the ECS stores:
// its `to_def` blob serialization and the `From<$ty>` conversions. The authoring
// metadata registry (`<Kind>Type`) is emitted separately by
// `__define_component_authoring!` so the two can live in different crates.
#[macro_export]
#[doc(hidden)]
macro_rules! __define_asset_kind {
    (
        asset_enum: $asset_enum:ident,
        asset_kind: $kind_variant:ident,
        $( $variant:ident => $ty:path, $disc:expr_2021 ),+ $(,)?
    ) => {
        #[derive(Debug)]
        pub enum $asset_enum {
            $( $variant($ty) ),+
        }

        impl $asset_enum {
            #[allow(dead_code)]
            pub fn to_def(&self) -> BlobAssetDef {
                match self {
                    $(
                        $asset_enum::$variant(c) => BlobAssetDef {
                            name: None,
                            kind: AssetKind::$kind_variant,
                            discriminant: $disc,
                            args_bytes: serde_json::to_vec(&c.to_args())
                                .expect(concat!("serialize ", stringify!($variant))),
                            payload: None,
                        }
                    ),+
                }
            }
        }

        $( impl From<$ty> for $asset_enum { fn from(c: $ty) -> Self { $asset_enum::$variant(c) } } )+
    };
}

#[macro_export]
macro_rules! define_components {
    ( $( $variant:ident => $ty:path ),+ $(,)? ) => {
        // The component type tag: one fieldless variant per component, in list
        // order, so each variant's `#[repr(u8)]` discriminant is its list
        // position (0, 1, 2, ...). `ComponentTag::$variant as u8` is that tag,
        // used both as the on-disk blob discriminant and as the in-memory ECS
        // `ComponentId`. The tag is assigned by position, not hand-written, and
        // is not a stable on-disk contract: a build regenerates the blob, so the
        // blob and the engine that loads it always agree. The authoring
        // `ComponentType` registry derives the same tag from this enum.
        #[repr(u8)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum ComponentTag {
            $( $variant ),+
        }

        $crate::__define_asset_kind! {
            asset_enum: ComponentAsset,
            asset_kind: Component,
            $( $variant => $ty, ComponentTag::$variant as u8 ),+
        }

        impl ComponentAsset {
            pub fn from_def(def: &BlobAssetDef) -> Result<Self, CnResult> {
                $(
                    if def.discriminant == ComponentTag::$variant as u8 {
                        let args = serde_json::from_slice::<<$ty as Component>::Args>(&def.args_bytes)?;
                        let mut c = <$ty as Component>::from_args(args);
                        if let Some(id) = def.name {
                            <$ty as Component>::inject_name(&mut c, id);
                        }
                        return Ok(ComponentAsset::$variant(c));
                    }
                )+
                Err(CnResult::AssetInvalidType)
            }

            // Inject a payload locator into the component after construction.
            // Delegates to `Component::inject_locator`; a no-op for types
            // that don't override that method.
            pub fn inject_locator(&mut self, locator: PayloadLocator) {
                match self {
                    $( ComponentAsset::$variant(c) => c.inject_locator(locator) ),+
                }
            }
        }

        // Per-type runtime storage. The `Column`-backed storage struct, the
        // `ComponentSlot` access trait, and the generic storage operations
        // (typed push, drain, mutable access, counts) are generated by the eas
        // storage macro -- shared and engine-agnostic. The asset-enum dispatch
        // (`push`, `all_defs`) is engine-specific and added in the impl below.
        concinnity_eas::define_component_storage! {
            storage: ComponentStorage,
            slot: ComponentSlot,
            $( $variant => $ty, ComponentTag::$variant as u8 ),+
        }

        impl ComponentStorage {
            // Dispatch a `ComponentAsset` variant into its typed column via the
            // generic typed push (which mints the Entity and stamps the tick).
            pub fn push(&mut self, asset: ComponentAsset) {
                match asset {
                    $( ComponentAsset::$variant(c) => { self.push_typed(c); } )+
                }
            }

            // Re-serialise every stored component as a `BlobAssetDef`.
            #[allow(dead_code)]
            pub fn all_defs(&self) -> Vec<BlobAssetDef> {
                let mut out = Vec::new();
                $(
                    for c in self.$variant.iter() {
                        out.push(BlobAssetDef {
                            name: None,
                            kind: AssetKind::Component,
                            discriminant: ComponentTag::$variant as u8,
                            args_bytes: serde_json::to_vec(&c.to_args())
                                .expect(concat!("serialize ", stringify!($variant))),
                            payload: None,
                        });
                    }
                )+
                out
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    // A standalone PipelineContext over empty storage, for exercising the
    // resource and event surfaces without a running world.
    fn parts() -> (ComponentStorage, BlobData, FrameProfile, Resources) {
        (
            ComponentStorage::default(),
            BlobData::empty(),
            FrameProfile::default(),
            Resources::new(),
        )
    }

    #[test]
    fn resources_round_trip_through_context() {
        let (mut c, mut b, mut p, mut r) = parts();
        let mut ctx = PipelineContext {
            components: &mut c,
            blob: &mut b,
            profile: &mut p,
            resources: &mut r,
        };
        assert!(ctx.resource::<u32>().is_none());
        assert_eq!(ctx.insert_resource(7u32), None);
        assert_eq!(ctx.resource::<u32>(), Some(&7));
        *ctx.resource_mut::<u32>().unwrap() = 9;
        assert_eq!(ctx.resource::<u32>(), Some(&9));
        // Re-inserting returns the previous value.
        assert_eq!(ctx.insert_resource(1u32), Some(9));
    }

    #[test]
    fn events_round_trip_through_context() {
        let (mut c, mut b, mut p, mut r) = parts();
        let mut ctx = PipelineContext {
            components: &mut c,
            blob: &mut b,
            profile: &mut p,
            resources: &mut r,
        };
        assert!(ctx.events::<u32>().is_none());
        ctx.events_mut::<u32>().send(1);
        ctx.events_mut::<u32>().send(2);

        let mut cursor = EventCursor::default();
        let seen: Vec<u32> = ctx
            .events::<u32>()
            .unwrap()
            .read(&mut cursor)
            .into_iter()
            .copied()
            .collect();
        assert_eq!(seen, vec![1, 2]);
        // The same cursor sees nothing new on a second read.
        assert!(ctx.events::<u32>().unwrap().read(&mut cursor).is_empty());
    }

    #[test]
    fn registration_predicates_follow_origin_and_payload() {
        let reg = |origin, payload| Registration {
            type_name: "T",
            origin,
            payload,
            default_args: None,
        };
        let external = reg(AssetOrigin::External, AssetPayload::Compiled);
        assert!(external.addable());
        assert!(external.serializable());
        assert!(external.runtime_present());
        assert!(external.needs_compilation());

        let runtime = reg(AssetOrigin::RuntimeOnly, AssetPayload::None);
        assert!(!runtime.addable());
        assert!(!runtime.serializable());
        assert!(runtime.runtime_present());
        assert!(!runtime.needs_compilation());

        let build = reg(AssetOrigin::BuildOnly, AssetPayload::None);
        assert!(!build.addable());
        assert!(build.serializable());
        assert!(!build.runtime_present());
    }

    #[test]
    fn component_asset_defs_round_trip_through_from_def() {
        let mut asset: ComponentAsset = crate::assets::Transform::default().into();
        // A payloadless component accepts a locator injection as a no-op.
        asset.inject_locator(PayloadLocator {
            blob_index: 0,
            offset: 0,
            len: 0,
        });
        let def = asset.to_def();
        assert_eq!(def.kind, AssetKind::Component);
        // The tag is Transform's position in the component list, derived from
        // `ComponentTag` so this stays correct if the list is reordered.
        assert_eq!(def.discriminant, ComponentTag::Transform as u8);
        let back = ComponentAsset::from_def(&def).unwrap();
        assert!(matches!(back, ComponentAsset::Transform(_)));
    }

    #[test]
    fn from_def_rejects_unknown_discriminants() {
        let def = BlobAssetDef {
            name: None,
            kind: AssetKind::Component,
            discriminant: 255,
            args_bytes: b"{}".to_vec(),
            payload: None,
        };
        assert_eq!(
            ComponentAsset::from_def(&def).unwrap_err(),
            CnResult::AssetInvalidType
        );
    }

    #[test]
    fn storage_push_dispatches_into_the_typed_column() {
        let mut storage = ComponentStorage::default();
        storage.push(crate::assets::Transform::default().into());
        let defs = storage.all_defs();
        assert_eq!(defs.len(), 1);
        // Transform's tag is its position in the component list.
        assert_eq!(defs[0].discriminant, ComponentTag::Transform as u8);
    }

    #[test]
    fn context_component_ops_cover_the_entity_lifecycle() {
        use crate::assets::{GlobalTransform, Transform};
        let (mut c, mut b, mut p, mut r) = parts();
        let mut ctx = PipelineContext {
            components: &mut c,
            blob: &mut b,
            profile: &mut p,
            resources: &mut r,
        };

        ctx.push(Transform::default());
        let e = ctx.components.push_typed(Transform::default());
        assert!(ctx.is_alive(e));
        assert_eq!(ctx.query::<Transform>().count(), 2);
        assert_eq!(ctx.query_with_entity::<Transform>().count(), 2);

        // Mutate through each of the mutable access paths.
        for t in ctx.query_mut::<Transform>() {
            t.position[0] = 1.0;
        }
        ctx.query_slice_mut::<Transform>()[0].position[1] = 2.0;
        ctx.get_mut::<Transform>(e).unwrap().position[2] = 3.0;
        assert_eq!(ctx.get::<Transform>(e).unwrap().position, [1.0, 0.0, 3.0]);

        // A second component on the same entity, then remove it again.
        ctx.insert(e, GlobalTransform::default());
        assert_eq!(ctx.join2::<Transform, GlobalTransform>().count(), 1);
        assert!(ctx.remove::<GlobalTransform>(e).is_some());
        assert!(ctx.remove::<GlobalTransform>(e).is_none());

        // Despawn kills the entity and its remaining components.
        ctx.despawn(e);
        assert!(!ctx.is_alive(e));
        assert_eq!(ctx.query::<Transform>().count(), 1);
        assert!(ctx.get::<Transform>(e).is_none());

        // Drain empties the column and returns the survivors.
        let drained = ctx.drain::<Transform>();
        assert_eq!(drained.len(), 1);
        assert_eq!(ctx.query::<Transform>().count(), 0);
    }

    #[test]
    fn read_payload_errors_on_an_empty_blob_store() {
        let (mut c, mut b, mut p, mut r) = parts();
        let mut ctx = PipelineContext {
            components: &mut c,
            blob: &mut b,
            profile: &mut p,
            resources: &mut r,
        };
        let loc = PayloadLocator {
            blob_index: 0,
            offset: 0,
            len: 4,
        };
        assert_eq!(ctx.read_payload(&loc).unwrap_err(), CnResult::FileIo);
        // Releasing a blob that does not exist is a no-op.
        ctx.release_blob(0);
    }
}
