// concinnity-eas/src/shard.rs
//
// Disjoint concurrent views over one component storage. `split_shards` takes
// the storage exclusively and a set of pairwise non-conflicting `Access`
// declarations, and hands out one `Shard` per declaration. Each shard can
// reach exactly the columns its declaration names: reads through `column`,
// whole-column writes through `values_mut`. Shards are `Send`, so a scheduler
// can run one system per shard on worker threads without sharing `&mut`.
//
// SAFETY MODEL. Column access goes through raw field projection
// (`ShardColumn::column_ptr`, generated by `define_component_storage!`), so
// no reference to the whole storage is ever materialized while shards are
// live. Soundness rests on one invariant, asserted at `split_shards`: the
// accesses are pairwise conflict-free, so a column is mutably reachable from
// at most one shard and never readable elsewhere while it is. Every accessor
// additionally checks its own declaration at runtime (release builds too), so
// an undeclared touch is a panic, not undefined behavior. Structural change
// (spawn/despawn/insert) is not expressible through a shard by construction.

use alloc::vec::Vec;
use core::marker::PhantomData;
use core::ptr::NonNull;

use crate::access::Access;
use crate::column::Column;
use crate::mask::ComponentId;
use crate::tick::AtomicTick;

/// Raw access to a component type's column inside storage `S`, plus the
/// storage's shared change tick. Generated by `define_component_storage!` for
/// every registered type; never implemented by hand.
pub trait ShardColumn<S>: Sized + 'static {
    const ID: u8;

    /// Project the column's address out of a raw storage pointer without
    /// creating a reference to the storage itself.
    ///
    /// # Safety
    /// `storage` must point to a live `S` for the duration of any use of the
    /// returned pointer.
    unsafe fn column_ptr(storage: *mut S) -> *mut Column<Self>;

    /// Project the storage's shared change-tick counter.
    ///
    /// # Safety
    /// As `column_ptr`.
    unsafe fn tick_ptr(storage: *mut S) -> *const AtomicTick;
}

pub struct Shard<'a, S> {
    storage: NonNull<S>,
    access: Access,
    _borrow: PhantomData<&'a mut S>,
}

// SAFETY: a shard only reaches columns its access declares, the split
// asserted pairwise conflict-freedom, and column payloads are `Send`/`Sync`
// bounded at the accessors below.
unsafe impl<S: Send> Send for Shard<'_, S> {}

impl<S> Shard<'_, S> {
    pub fn access(&self) -> Access {
        self.access
    }

    // The declared-read view of C's column.
    pub fn column<C: ShardColumn<S> + Sync>(&self) -> &Column<C> {
        assert!(
            self.access.may_read_component(ComponentId::new(C::ID)),
            "shard read of undeclared component id {}",
            C::ID,
        );
        // SAFETY: storage outlives 'a (PhantomData borrow); the split
        // invariant guarantees no other shard writes this column.
        unsafe { &*C::column_ptr(self.storage.as_ptr()) }
    }

    // The declared-write view of C's column, stamped like
    // `ComponentStorage::values_mut` (bulk tick: any element may be written).
    pub fn values_mut<C: ShardColumn<S> + Send>(&mut self) -> &mut [C] {
        assert!(
            self.access.may_write_component(ComponentId::new(C::ID)),
            "shard write of undeclared component id {}",
            C::ID,
        );
        // SAFETY: the split invariant makes this shard the only reacher of
        // this column; the tick counter is atomic and shared by design.
        unsafe {
            let tick = (*C::tick_ptr(self.storage.as_ptr())).bump();
            (*C::column_ptr(self.storage.as_ptr())).values_mut(tick)
        }
    }
}

// Split one storage into disjoint concurrent views, one per access
// declaration. Panics when any pair conflicts or any declaration is
// exclusive: that is a scheduler bug, and continuing would be unsound.
pub fn split_shards<'a, S>(storage: &'a mut S, accesses: &[Access]) -> Vec<Shard<'a, S>> {
    for (i, a) in accesses.iter().enumerate() {
        assert!(!a.is_exclusive(), "exclusive access cannot share a split");
        for b in accesses.iter().skip(i + 1) {
            assert!(
                !a.conflicts_with(*b),
                "conflicting accesses handed to split_shards",
            );
        }
    }
    let ptr = NonNull::from(storage);
    accesses
        .iter()
        .map(|&access| Shard {
            storage: ptr,
            access,
            _borrow: PhantomData,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    // The generated test storage exposes the full storage surface; these
    // tests exercise only the shard-relevant slice of it.
    #![allow(dead_code)]

    use super::*;
    use crate::mask::ComponentMask;

    #[derive(Default, Debug, PartialEq, Clone, Copy)]
    pub struct Pos(u32);

    #[derive(Default, Debug, PartialEq, Clone, Copy)]
    pub struct Vel(i32);

    crate::define_component_storage! {
        storage: ShardTestStorage,
        slot: ShardTestSlot,
        Pos => Pos, 1,
        Vel => Vel, 2,
    }

    fn mask(ids: &[u8]) -> ComponentMask {
        let mut m = ComponentMask::EMPTY;
        for &id in ids {
            m.insert(ComponentId::new(id));
        }
        m
    }

    fn filled() -> ShardTestStorage {
        let mut s = ShardTestStorage::default();
        for i in 0..1000 {
            s.push_typed(Pos(i));
            s.push_typed(Vel(i as i32));
        }
        s
    }

    #[test]
    fn disjoint_writers_mutate_their_own_columns() {
        let mut s = filled();
        let a = Access::new().writes_components(mask(&[1]));
        let b = Access::new().writes_components(mask(&[2]));
        let mut shards = split_shards(&mut s, &[a, b]);
        let mut sb = shards.pop().unwrap();
        let mut sa = shards.pop().unwrap();
        std::thread::scope(|scope| {
            scope.spawn(move || {
                for p in sa.values_mut::<Pos>() {
                    p.0 += 1;
                }
            });
            scope.spawn(move || {
                for v in sb.values_mut::<Vel>() {
                    v.0 -= 1;
                }
            });
        });
        assert_eq!(
            s.get::<Pos>(<Pos as ShardTestSlot>::slot(&s).entities()[0]),
            Some(&Pos(1))
        );
        assert!(s.Vel.iter().all(|v| v.0 < 1000));
    }

    #[test]
    fn reader_and_disjoint_writer_share_a_split() {
        let mut s = filled();
        let reader = Access::new().reads_components(mask(&[1]));
        let writer = Access::new().writes_components(mask(&[2]));
        let mut shards = split_shards(&mut s, &[reader, writer]);
        let mut w = shards.pop().unwrap();
        let r = shards.pop().unwrap();
        std::thread::scope(|scope| {
            scope.spawn(move || {
                let col = r.column::<Pos>();
                assert_eq!(col.len(), 1000);
                assert!(col.iter().any(|p| p.0 == 999));
            });
            scope.spawn(move || {
                for v in w.values_mut::<Vel>() {
                    v.0 = 0;
                }
            });
        });
        assert!(s.Vel.iter().all(|v| v.0 == 0));
    }

    #[test]
    fn shard_writes_advance_change_detection() {
        let mut s = filled();
        let before = s.column_ticks::<Pos>();
        {
            let a = Access::new().writes_components(mask(&[1]));
            let mut shards = split_shards(&mut s, &[a]);
            let _ = shards[0].values_mut::<Pos>();
        }
        let after = s.column_ticks::<Pos>();
        assert!(after.bulk.is_newer_than(before.bulk));
    }

    #[test]
    #[should_panic(expected = "conflicting accesses")]
    fn conflicting_split_panics() {
        let mut s = filled();
        let a = Access::new().writes_components(mask(&[1]));
        let b = Access::new().reads_components(mask(&[1]));
        let _ = split_shards(&mut s, &[a, b]);
    }

    #[test]
    #[should_panic(expected = "exclusive access cannot share")]
    fn exclusive_split_panics() {
        let mut s = filled();
        let _ = split_shards(&mut s, &[Access::new().exclusive()]);
    }

    #[test]
    #[should_panic(expected = "undeclared component id")]
    fn undeclared_read_panics() {
        let mut s = filled();
        let a = Access::new().reads_components(mask(&[1]));
        let shards = split_shards(&mut s, &[a]);
        let _ = shards[0].column::<Vel>();
    }

    #[test]
    #[should_panic(expected = "undeclared component id")]
    fn declared_read_does_not_grant_write() {
        let mut s = filled();
        let a = Access::new().reads_components(mask(&[1]));
        let mut shards = split_shards(&mut s, &[a]);
        let _ = shards[0].values_mut::<Pos>();
    }

    // Many threads hammering disjoint columns through shards while the main
    // thread polls the shared tick: the atomic counter and the disjointness
    // invariant hold under real concurrency (run under `cargo test` normally;
    // meaningful under TSan/miri as the stress surface for this module).
    #[test]
    fn concurrent_stress_disjoint_columns() {
        let mut s = filled();
        for _ in 0..8 {
            let a = Access::new().writes_components(mask(&[1]));
            let b = Access::new().writes_components(mask(&[2]));
            let mut shards = split_shards(&mut s, &[a, b]);
            let mut sb = shards.pop().unwrap();
            let mut sa = shards.pop().unwrap();
            std::thread::scope(|scope| {
                scope.spawn(move || {
                    for _ in 0..50 {
                        for p in sa.values_mut::<Pos>() {
                            p.0 = p.0.wrapping_add(1);
                        }
                    }
                });
                scope.spawn(move || {
                    for _ in 0..50 {
                        for v in sb.values_mut::<Vel>() {
                            v.0 = v.0.wrapping_sub(1);
                        }
                    }
                });
            });
        }
        // 8 rounds x 50 sweeps x 2 columns of bulk writes all stamped.
        assert!(s.column_ticks::<Pos>().bulk.get() > 0);
    }
}
