// src/cli/list.rs
use concinnity_cook::ComponentType;
use concinnity_cook::world::{find_world_jsonl, parse_world_jsonl, resolve_includes};

// Resolve the world path the same way every other subcommand does: an explicit
// existing path wins, otherwise discover from .concinnity/worlds/ or cwd.
pub(crate) fn resolve_world_path(json_path: Option<&str>) -> std::io::Result<String> {
    match json_path {
        Some(p) if std::path::Path::new(p).exists() => Ok(p.to_string()),
        _ => find_world_jsonl(None),
    }
}

// Provenance of one expanded-world row: declared in the file, added by an
// injection pass, or generated by a build-time macro expansion.
pub(crate) fn provenance(loaded: &concinnity_cook::world::LoadedWorld, name: &str) -> String {
    if loaded.authored.iter().any(|n| n == name) {
        return "authored".to_string();
    }
    if let Some(i) = loaded.injected.iter().find(|i| i.name == name) {
        return format!("injected:{}", i.injected_by);
    }
    "expanded".to_string()
}

pub fn list(json_path: Option<&str>, expanded: bool) -> std::io::Result<()> {
    let json_path = resolve_world_path(json_path)?;

    let content = std::fs::read_to_string(&json_path).map_err(|e| {
        tracing::error!("Could not read {}: {}", json_path, e);
        e
    })?;

    if expanded {
        return list_expanded(&content, &json_path);
    }

    let assets = parse_world_jsonl(&content).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("Failed to parse {}: {}", json_path, e),
        )
    })?;

    let raw = resolve_includes(assets)?;

    if raw.is_empty() {
        println!("{} has no assets.", json_path);
        return Ok(());
    }

    // collect rows, then print aligned
    struct Row {
        name: String,
        type_str: String,
        origin: String,
        payload: String,
    }

    let rows: Vec<Row> = raw
        .iter()
        .map(|v| {
            let name = v
                .get("name")
                .and_then(|n| n.as_str())
                .unwrap_or("(unnamed)")
                .to_string();
            let type_str = v
                .get("type")
                .and_then(|t| t.as_str())
                .unwrap_or("?")
                .to_string();

            let (origin, payload) = if let Some(ct) = ComponentType::parse(&type_str) {
                let r = ct.registration();
                (format!("{:?}", r.origin), format!("{:?}", r.payload))
            } else {
                ("?".to_string(), "?".to_string())
            };

            Row {
                name,
                type_str,
                origin,
                payload,
            }
        })
        .collect();

    let w_name = rows.iter().map(|r| r.name.len()).max().unwrap_or(4).max(4);
    let w_type = rows
        .iter()
        .map(|r| r.type_str.len())
        .max()
        .unwrap_or(4)
        .max(4);
    let w_origin = rows
        .iter()
        .map(|r| r.origin.len())
        .max()
        .unwrap_or(6)
        .max(6);

    println!(
        "{:<w_name$}  {:<w_type$}  {:<w_origin$}  PAYLOAD",
        "NAME",
        "TYPE",
        "ORIGIN",
        w_name = w_name,
        w_type = w_type,
        w_origin = w_origin,
    );
    println!("{}", "-".repeat(w_name + w_type + w_origin + 16));

    for r in &rows {
        println!(
            "{:<w_name$}  {:<w_type$}  {:<w_origin$}  {}",
            r.name,
            r.type_str,
            r.origin,
            r.payload,
            w_name = w_name,
            w_type = w_type,
            w_origin = w_origin,
        );
    }

    println!("\n{} asset(s) in {}", rows.len(), json_path);
    Ok(())
}

// The expanded world: every asset the build produces, with its provenance.
// Runs the same front half as `cn build` (expansion passes, injection,
// semantic validation), so the listing is exactly what lands in the blob.
fn list_expanded(content: &str, json_path: &str) -> std::io::Result<()> {
    let loaded = concinnity_cook::prepare_world(content)
        .map_err(|errs| concinnity_cook::check::report_validation_errors(&errs))?;

    if loaded.assets.is_empty() {
        println!("{} expands to no assets.", json_path);
        return Ok(());
    }

    let rows: Vec<(String, String, String)> = loaded
        .assets
        .iter()
        .map(|a| {
            (
                a.name.clone(),
                a.asset_type.clone(),
                provenance(&loaded, &a.name),
            )
        })
        .collect();

    let w_name = rows.iter().map(|r| r.0.len()).max().unwrap_or(4).max(4);
    let w_type = rows.iter().map(|r| r.1.len()).max().unwrap_or(4).max(4);

    println!(
        "{:<w_name$}  {:<w_type$}  PROVENANCE",
        "NAME",
        "TYPE",
        w_name = w_name,
        w_type = w_type,
    );
    println!("{}", "-".repeat(w_name + w_type + 14));

    for (name, type_str, prov) in &rows {
        println!(
            "{:<w_name$}  {:<w_type$}  {}",
            name,
            type_str,
            prov,
            w_name = w_name,
            w_type = w_type,
        );
    }

    let injected = loaded.injected.len();
    println!(
        "\n{} asset(s) after expansion ({} injected) in {}",
        rows.len(),
        injected,
        json_path
    );
    println!("Use `cn explain <name>` to print an entry for overriding.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_world(content: &str) -> (tempfile::TempDir, String) {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("world.jsonl");
        std::fs::write(&path, content).unwrap();
        (dir, path.to_string_lossy().into_owned())
    }

    #[test]
    fn resolve_world_path_prefers_an_explicit_existing_path() {
        let (_dir, path) = write_world("");
        assert_eq!(resolve_world_path(Some(&path)).unwrap(), path);
    }

    fn loaded_world_fixture() -> concinnity_cook::world::LoadedWorld {
        concinnity_cook::world::LoadedWorld {
            assets: Vec::new(),
            injected: vec![concinnity_cook::world::InjectedAsset {
                name: "debug_hud".to_string(),
                asset_type: "DebugHud".to_string(),
                args: serde_json::json!({}),
                injected_by: "debug_hud",
            }],
            authored: vec!["cam".to_string()],
        }
    }

    #[test]
    fn provenance_reports_authored_names() {
        assert_eq!(provenance(&loaded_world_fixture(), "cam"), "authored");
    }

    #[test]
    fn provenance_reports_the_injection_pass() {
        assert_eq!(
            provenance(&loaded_world_fixture(), "debug_hud"),
            "injected:debug_hud"
        );
    }

    #[test]
    fn provenance_falls_back_to_expanded() {
        assert_eq!(provenance(&loaded_world_fixture(), "anything"), "expanded");
    }

    #[test]
    fn list_of_an_empty_world_is_ok() {
        let (_dir, path) = write_world("");
        list(Some(&path), false).unwrap();
    }

    #[test]
    fn list_prints_known_and_unknown_types() {
        // GraphicsConfig resolves through the registry; the made-up type
        // falls back to "?" origin / payload without erroring.
        let (_dir, path) = write_world(concat!(
            "{\"name\":\"gfx\",\"type\":\"GraphicsConfig\",\"args\":{}}\n",
            "{\"name\":\"odd\",\"type\":\"NotARealAssetType\",\"args\":{}}\n",
            "{\"type\":\"GraphicsConfig\",\"args\":{}}\n",
        ));
        list(Some(&path), false).unwrap();
    }

    #[test]
    fn list_with_invalid_json_errors() {
        let (_dir, path) = write_world("{ not json\n");
        let err = list(Some(&path), false).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
    }

    #[test]
    fn list_expanded_runs_the_build_front_half() {
        let (_dir, path) =
            write_world("{\"name\":\"gfx\",\"type\":\"GraphicsConfig\",\"args\":{}}\n");
        list(Some(&path), true).unwrap();
    }

    #[test]
    fn list_expanded_rejects_an_unknown_asset_type() {
        let (_dir, path) =
            write_world("{\"name\":\"odd\",\"type\":\"NotARealAssetType\",\"args\":{}}\n");
        assert!(list(Some(&path), true).is_err());
    }
}
