[package]
name = "concinnity-bench"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "concinnity_bench"
doctest = false
bench = false

[build-dependencies]
concinnity-toolchain = { workspace = true }

[dependencies]
concinnity-asset = { workspace = true }
concinnity-cook = { workspace = true }
concinnity-core = { workspace = true }
concinnity-engine = { workspace = true }
concinnity-memory = { workspace = true }
concinnity-render = { workspace = true }

[[bench]]
name = "anim"
path = "anim.rs"
harness = false

[[bench]]
name = "cook"
path = "cook.rs"
harness = false

[[bench]]
name = "engine"
path = "engine.rs"
harness = false

[[bench]]
name = "render"
path = "render.rs"
harness = false

[lints]
workspace = true
