[package]
name = "concinnity-bench"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "concinnity_bench"
doctest = false
bench = false

[dependencies]
concinnity-asset = { path = "../crates/concinnity-asset" }
concinnity-blob = { path = "../crates/concinnity-blob" }
concinnity-cook = { path = "../crates/concinnity-cook" }
concinnity-cpu = { path = "../crates/concinnity-cpu" }
concinnity-eas = { path = "../crates/concinnity-eas" }
concinnity-engine = { path = "../crates/concinnity-engine" }
concinnity-memory = { path = "../crates/concinnity-memory" }
concinnity-physics = { path = "../crates/concinnity-physics" }
concinnity-render = { path = "../crates/concinnity-render" }

[[bench]]
name = "anim"
path = "anim.rs"
harness = false

[[bench]]
name = "cook"
path = "cook.rs"
harness = false

[[bench]]
name = "ecs"
path = "ecs.rs"
harness = false

[[bench]]
name = "engine"
path = "engine.rs"
harness = false

[[bench]]
name = "memory"
path = "memory.rs"
harness = false

[[bench]]
name = "physics"
path = "physics.rs"
harness = false

[[bench]]
name = "render"
path = "render.rs"
harness = false
