//! The authored schema as static data: every authored type's name, rustdoc,
//! and fields or values, generated by `#[derive(AssetFields)]` and
//! `#[derive(Vocabulary)]`.
//!
//! A field's type is described in JSON terms ([`FieldType`]), not Rust ones:
//! a `Vec` is an array, a [`Ref`](super::Ref) is a reference by name, a type
//! with its own derive is a nested object or a closed set of strings. Defaults
//! are not written down here but produced on demand, by running the type's
//! `Default` the way serde would for an omitted key ([`FieldDefault`]), so
//! they are exact by construction. What turns one into JSON is the tooling's
//! business; this crate holds no JSON.
//!
//! Present only with the `schema` feature, which the authoring tools enable:
//! the rustdoc strings never reach a shipped player.

mod described;
#[doc(hidden)]
pub mod probe;

use alloc::boxed::Box;

/// One authored type: a struct with named fields or a string-valued enum.
#[derive(Clone, Copy)]
pub struct TypeSchema {
    /// The type's Rust identifier.
    pub name: &'static str,
    /// The type's rustdoc, one line per doc line, without rustdoc's leading
    /// space.
    pub doc: &'static str,
    /// The fields or values the type serializes as.
    pub body: Body,
    /// The value an omitted field takes from the whole type, for a type whose
    /// serde default is the container's. `None` when the type has no container
    /// default, or when its default cannot be serialized.
    pub default: Option<fn() -> Option<DefaultValue>>,
}

/// What a [`TypeSchema`] serializes as.
#[derive(Clone, Copy)]
pub enum Body {
    /// A JSON object: the struct's authored fields, in declaration order.
    Fields(&'static [FieldSchema]),
    /// A JSON string: the enum's authored names, in declaration order.
    Values(&'static [ValueSchema]),
}

/// One authored field of a struct.
#[derive(Clone, Copy)]
pub struct FieldSchema {
    /// The authored key. Empty for a flattened field, whose own fields sit at
    /// the parent's level.
    pub key: &'static str,
    /// The field's rustdoc, one line per doc line.
    pub doc: &'static str,
    /// The field's JSON-shaped type.
    pub ty: fn() -> FieldType,
    /// What an omitted key deserializes to.
    pub default: FieldDefault,
}

impl FieldSchema {
    /// Whether the field's own fields sit at the parent's level.
    pub fn is_flattened(&self) -> bool {
        self.key.is_empty()
    }
}

/// One authored name of a string-valued enum.
#[derive(Clone, Copy)]
pub struct ValueSchema {
    /// The string the variant is written as.
    pub name: &'static str,
    /// The variant's rustdoc, one line per doc line.
    pub doc: &'static str,
}

/// A field's type, in the terms a JSON author sees.
#[derive(Clone, Copy)]
pub enum FieldType {
    /// `true` or `false`.
    Bool,
    /// A number with a fractional part.
    Float,
    /// A whole number.
    Integer,
    /// Free text.
    Str,
    /// The `$id` of another asset, of one of these registry types (any declared
    /// asset when empty).
    Reference(&'static [&'static str]),
    /// A JSON object with no described shape.
    Object,
    /// The inner type, or `null`.
    Optional(fn() -> FieldType),
    /// A list of the element type, of a fixed length when `len` is set.
    Array {
        /// The element type.
        elem: fn() -> FieldType,
        /// The fixed length of a Rust array; `None` for a `Vec`.
        len: Option<usize>,
    },
    /// A JSON object of a described struct.
    Nested(&'static TypeSchema),
    /// One of a described enum's names.
    Enum(&'static TypeSchema),
}

/// What an omitted key deserializes to, following serde's own precedence: the
/// field's `default` attribute, then the container's, then `None` for an
/// `Option`.
#[derive(Clone, Copy)]
pub enum FieldDefault {
    /// The key must be present.
    Required,
    /// The field's value in the containing type's default
    /// ([`TypeSchema::default`]).
    Container,
    /// The field's own default. `None` from the call when the value cannot be
    /// serialized.
    Value(fn() -> Option<DefaultValue>),
    /// `null`: an `Option` with no default attribute.
    Null,
}

/// A default value, ready to serialize into whatever format the tooling
/// writes.
pub type DefaultValue = Box<dyn erased_serde::Serialize>;

/// A field type with a JSON-shaped description.
///
/// `#[derive(AssetFields)]` implements it for a struct (a [`FieldType::Nested`])
/// and `#[derive(Vocabulary)]` for an enum (a [`FieldType::Enum`]); this module
/// implements it for the scalars and references.
pub trait Described {
    /// The type as a field of another type sees it.
    const TYPE: FieldType;
}

/// A derived type's whole schema.
pub trait Schema {
    /// The type's schema.
    const SCHEMA: &'static TypeSchema;
}

#[cfg(test)]
mod tests;
